trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
      
- stage: Deploy
  jobs:
  - job: Deploy
    